Repository kelektiv/node-cron, pull requests merged in 2023-09, with the labels that each got.

#685 fix: added fractional offset support
  README.md
  lib/time.js
  tests/cron.test.js
  tests/crontime.test.js
Labels: bug

#694 refactor!: migrate to TypeScript
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .prettierignore
  .vscode/launch.json
  README.md
  bower.json
  examples/at_10_minutes.js
  examples/at_midnight.js
  examples/basic.js
  examples/complex_expr.js
  examples/every_10_minutes.js
  examples/every_30_minutes_between_9_and_5.js
  examples/get_next_runs.js
  examples/in_the_past.js
  examples/is_crontime_valid.js
  examples/is_job_running.js
  examples/long_running_on_tick.js
  examples/mon_to_fri_at_11_30.js
  examples/multiple_jobs.js
  examples/object_param.js
  examples/run_at_specific_date.js
  examples/time_dom_syntax_with_tz.js
  examples/utc_offset_syntax.js
  jest.config.json
  lib/cron.js
  lib/job.js
  lib/time.js
  package-lock.json
  package.json
  src/constants.ts
  src/index.ts
  src/job.ts
  src/time.ts
  src/types/cron.types.ts
  src/types/utils.ts
  src/utils.ts
  tests/cron.test.ts
  tests/crontime.test.ts
  tsconfig.build.json
  tsconfig.json
  types/index.d.ts
  types/index.test-d.ts
Labels: typescript

#695 docs(readme): remove outdated informations
  README.md
Labels: documentation

#699 feat!: rework utcOffset parameter
  README.md
  src/errors.ts
  src/job.ts
  src/time.ts
  src/types/cron.types.ts
  tests/cron.test.ts
  tests/crontime.test.ts
Labels: enhancement
